# Generated by Django 5.1 on 2024-09-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("originweb_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("cover", models.TextField()),
                ("subtitle", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("link", models.CharField(max_length=2000)),
            ],
        ),
    ]
