# Generated by Django 5.1 on 2024-10-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("originweb_backend", "0002_productsmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExampleModel",
        ),
        migrations.AlterModelOptions(
            name="productsmodel",
            options={"managed": False},
        ),
    ]
