# Generated by Django 5.1 on 2024-10-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("originweb_backend", "0003_delete_examplemodel_alter_productsmodel_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productsmodel",
            table="originweb_backend_productsmodel",
        ),
    ]
