# Generated by Django 5.1 on 2025-01-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("originweb_backend", "0004_alter_productsmodel_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsmodel",
            options={"managed": True},
        ),
    ]
