# Generated by Django 5.1 on 2025-01-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "originweb_backend",
            "0006_productsmodel_category_productsmodel_createtime_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsmodel",
            options={"managed": False},
        ),
    ]
